# Generated by Django 5.0.9 on 2024-11-01 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Visit',
            new_name='PageVisit',
        ),
    ]
